source 'https://rubygems.org'

# Specify your gem's dependencies in reedb.gemspec
gemspec

# Encryption
gem 'aes', '>=0.5.0'
gem 'twofish', '>=1.0.5'

# Data management
gem 'bson', '~> 2.3.0' 
gem 'json', '~> 1.8.2' 