source 'https://rubygems.org'

# Specify your gem's dependencies in reedb.gemspec
gemspec

# Security!
gem 'aes', '>=0.5.0'
gem 'twofish', '>=1.0.5'
gem 'digest-tiger', '~> 1.0.2'

# Data storage
gem 'json', '~> 1.8.2' 